const { SlashCommandBuilder, PermissionFlagsBits, EmbedBuilder, ActionRowBuilder, ButtonBuilder, ButtonStyle } = require('discord.js');
const store = require('../db/database');
const { record, doAction, actionEmbed } = require('../services/moderation');

const mod = PermissionFlagsBits.ModerateMembers;
const admin = PermissionFlagsBits.ManageGuild;
const ownerId = () => process.env.DISCORD_OWNER_ID || '1094063045866684496';
function requirePermission(i, permission) { if (!i.memberPermissions.has(permission) && i.user.id !== ownerId()) throw new Error('You do not have the required server permission.'); }
const commands = [
 new SlashCommandBuilder().setName('warn').setDescription('Record a warning for a member').addUserOption(o=>o.setName('member').setDescription('Member').setRequired(true)).addStringOption(o=>o.setName('reason').setDescription('Reason').setRequired(true).setMaxLength(500)),
 new SlashCommandBuilder().setName('timeout').setDescription('Temporarily timeout a member').addUserOption(o=>o.setName('member').setDescription('Member').setRequired(true)).addIntegerOption(o=>o.setName('minutes').setDescription('Duration, 1–40320 minutes').setRequired(true).setMinValue(1).setMaxValue(40320)).addStringOption(o=>o.setName('reason').setDescription('Reason').setMaxLength(500)),
 new SlashCommandBuilder().setName('kick').setDescription('Kick a member').addUserOption(o=>o.setName('member').setDescription('Member').setRequired(true)).addStringOption(o=>o.setName('reason').setDescription('Reason').setMaxLength(500)),
 new SlashCommandBuilder().setName('ban').setDescription('Ban a member with confirmation').addUserOption(o=>o.setName('member').setDescription('Member').setRequired(true)).addStringOption(o=>o.setName('reason').setDescription('Reason').setMaxLength(500)),
 new SlashCommandBuilder().setName('purge').setDescription('Delete recent messages').addIntegerOption(o=>o.setName('amount').setDescription('1–100').setMinValue(1).setMaxValue(100).setRequired(true)),
 new SlashCommandBuilder().setName('slowmode').setDescription('Set channel slowmode').addIntegerOption(o=>o.setName('seconds').setDescription('0–21600 seconds').setMinValue(0).setMaxValue(21600).setRequired(true)),
 new SlashCommandBuilder().setName('modlog').setDescription('Show recent moderation actions').addUserOption(o=>o.setName('member').setDescription('Filter by member')),
 new SlashCommandBuilder().setName('config').setDescription('Configure server features').addSubcommand(s=>s.setName('welcome').setDescription('Set welcome channel').addChannelOption(o=>o.setName('channel').setDescription('Channel').setRequired(true))).addSubcommand(s=>s.setName('welcomemessage').setDescription('Set welcome text; supports {user} and {server}').addStringOption(o=>o.setName('message').setDescription('Welcome text').setMaxLength(1000).setRequired(true))).addSubcommand(s=>s.setName('filter').setDescription('Enable the bilingual word filter').addBooleanOption(o=>o.setName('enabled').setDescription('Enabled?').setRequired(true)).addStringOption(o=>o.setName('action').setDescription('Moderator action').addChoices({name:'Flag only',value:'flag'},{name:'Delete',value:'delete'}).setRequired(true))).addSubcommand(s=>s.setName('words').setDescription('Replace filter terms (comma-separated)').addStringOption(o=>o.setName('terms').setDescription('Terms; stored privately').setRequired(true).setMaxLength(1500))).addSubcommand(s=>s.setName('analytics').setDescription('Enable aggregate activity analytics').addBooleanOption(o=>o.setName('enabled').setDescription('Enabled?').setRequired(true))).addSubcommand(s=>s.setName('conversation').setDescription('Enable occasional conversational replies').addBooleanOption(o=>o.setName('enabled').setDescription('Enabled?').setRequired(true))).addSubcommand(s=>s.setName('leveling').setDescription('Toggle text activity leveling').addBooleanOption(o=>o.setName('enabled').setDescription('Enabled?').setRequired(true))).addSubcommand(s=>s.setName('numbering').setDescription('Toggle sequential member numbers').addBooleanOption(o=>o.setName('enabled').setDescription('Enabled?').setRequired(true))),
 new SlashCommandBuilder().setName('welcome-test').setDescription('Preview the configured welcome message'),
 new SlashCommandBuilder().setName('member').setDescription('Look up a member in this server').addUserOption(o=>o.setName('user').setDescription('Member').setRequired(true)),
 new SlashCommandBuilder().setName('analytics').setDescription('View aggregate activity analytics'),
 new SlashCommandBuilder().setName('announce').setDescription('Send an embed announcement here').addStringOption(o=>o.setName('title').setDescription('Title').setRequired(true).setMaxLength(256)).addStringOption(o=>o.setName('message').setDescription('Message').setRequired(true).setMaxLength(3000)),
 new SlashCommandBuilder().setName('help').setDescription('Show bot commands')
].map(c=>c.toJSON());

const norm = s => s.toLowerCase().normalize('NFKC').replace(/[أإآٱ]/g,'ا').replace(/ى/g,'ي').replace(/ة/g,'ه').replace(/[ًٌٍَُِّْـ]/g,'').replace(/[ـ\u200b-\u200f]/g,'');
async function execute(i) {
 const g=i.guildId, user=i.options.getUser('member'), reason=i.options.getString('reason') || 'No reason provided';
 switch(i.commandName) {
 case 'warn': { requirePermission(i,mod); await store.addWarning(g,user.id,i.user.id,reason); await record(g,user.id,i.user.id,'warn',reason); return i.reply({content:`Warning recorded for ${user.tag}.`,ephemeral:true}); }
 case 'timeout': { const m=await i.guild.members.fetch(user.id); await doAction(i,'timeout',m,reason,i.options.getInteger('minutes')); return i.reply({content:`${user.tag} timed out.`,ephemeral:true}); }
 case 'kick': case 'ban': { const m=await i.guild.members.fetch(user.id); const kind=i.commandName; const row=new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`confirm:${kind}:${user.id}:${i.user.id}`).setLabel(`Confirm ${kind}`).setStyle(ButtonStyle.Danger),new ButtonBuilder().setCustomId('cancel').setLabel('Cancel').setStyle(ButtonStyle.Secondary)); return i.reply({content:`Confirm ${kind} for **${user.tag}**? Reason: ${reason}`,components:[row],ephemeral:true}); }
 case 'purge': { requirePermission(i,PermissionFlagsBits.ManageMessages); const n=i.options.getInteger('amount'); const msgs=await i.channel.bulkDelete(n,true); return i.reply({content:`Deleted ${msgs.size} recent messages.`,ephemeral:true}); }
 case 'slowmode': requirePermission(i,PermissionFlagsBits.ManageChannels); await i.channel.setRateLimitPerUser(i.options.getInteger('seconds')); return i.reply({content:'Slowmode updated.',ephemeral:true});
 case 'modlog': { requirePermission(i,mod); const member=i.options.getUser('member'); const rows=await store.recentActions(g,member?.id); return i.reply({embeds:[actionEmbed('Recent moderation actions').setDescription(rows.length?rows.map(r=>`**${r.action}** <@${r.target_id}> by <@${r.moderator_id}> — ${r.reason} (${r.created_at.toISOString()})`).join('\n'):'No actions recorded.')],ephemeral:true}); }
 case 'config': { requirePermission(i,admin); const sub=i.options.getSubcommand(); const fields={welcome:['welcome_channel',i.options.getChannel('channel')?.id],welcomemessage:['welcome_message',i.options.getString('message')],filter:['filter_enabled',i.options.getBoolean('enabled')?1:0],analytics:['analytics_enabled',i.options.getBoolean('enabled')?1:0],conversation:['conversation_enabled',i.options.getBoolean('enabled')?1:0],leveling:['leveling_enabled',i.options.getBoolean('enabled')?1:0],numbering:['member_numbering',i.options.getBoolean('enabled')?1:0]};
 if(sub==='filter') await store.updateSettings(g,{filter_enabled:Boolean(fields.filter[1]),filter_action:i.options.getString('action')});
 else if(sub==='words') await store.updateSettings(g,{filter_words:i.options.getString('terms').split(',').map(x=>x.trim()).filter(Boolean)});
 else await store.updateSettings(g,{[fields[sub][0]]:fields[sub][1]});
 return i.reply({content:`${sub} setting saved for this server.`,ephemeral:true}); }
 case 'welcome-test': { requirePermission(i,admin); const s=await store.settings(g); return i.reply({embeds:[new EmbedBuilder().setColor(s.welcome_color).setDescription(s.welcome_message.replaceAll('{user}',`<@${i.user.id}>`).replaceAll('{server}',i.guild.name))],ephemeral:true}); }
 case 'member': { const u=i.options.getUser('user'); const m=await i.guild.members.fetch(u.id).catch(()=>null); if(!m)return i.reply({content:'That user is not a member of this server.',ephemeral:true}); const s=await store.settings(g); const num=await store.getMember(g,u.id); return i.reply({embeds:[actionEmbed(`Member: ${u.tag}`).setThumbnail(u.displayAvatarURL()).addFields({name:'Joined',value:m.joinedAt?.toISOString()||'Unknown',inline:true},{name:'Account created',value:u.createdAt.toISOString(),inline:true},...(s.member_numbering&&num?.member_number?[{name:'Member number',value:String(num.member_number),inline:true}]:[]))],ephemeral:true}); }
 case 'analytics': { requirePermission(i,admin); const since=new Date(Date.now()-7*86400000).toISOString().slice(0,10); const rows=await store.activitySummary(g,since); return i.reply({embeds:[actionEmbed('Server activity · 7 days').setDescription(`Messages: **${rows.messages||0}**\nVoice member-minutes: **${rows.voice||0}**\nAggregated hourly totals only; message content is not stored.`)],ephemeral:true}); }
 case 'announce': { requirePermission(i,PermissionFlagsBits.ManageMessages); const e=new EmbedBuilder().setTitle(i.options.getString('title')).setDescription(i.options.getString('message')).setColor(0x5865F2).setFooter({text:`Posted by ${i.user.username}`}).setTimestamp(); await i.channel.send({embeds:[e]}); return i.reply({content:'Announcement sent.',ephemeral:true}); }
 case 'help': return i.reply({content:'Moderation: /warn /timeout /kick /ban /purge /slowmode /modlog\nServer: /config /welcome-test /member /analytics /announce\nCommands use ephemeral replies for private results. Configure features with /config.',ephemeral:true});
 }
}
module.exports={commands,execute,norm};
